# Generated by Django 4.1.5 on 2023-07-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0002_sensor_work'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='../static/img/default.png', upload_to='users/%Y/%m/%d', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sensor',
            field=models.ManyToManyField(blank=True, to='esp_sensor.sensor', verbose_name='Датчик'),
        ),
    ]
