# Generated by Django 4.2.3 on 2024-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('max_usages', models.IntegerField()),
            ],
        ),
    ]
