# Generated by Django 4.2.3 on 2024-05-24 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_registrationcode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrationcode',
            options={'verbose_name': 'Регистрационный код', 'verbose_name_plural': 'Регистрационный код'},
        ),
        migrations.AddField(
            model_name='profile',
            name='last_activity',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Последняя активность'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='code',
            field=models.CharField(max_length=10, unique=True, verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='max_usages',
            field=models.IntegerField(verbose_name='Максимальное кол-во использований'),
        ),
        migrations.AlterField(
            model_name='registrationcode',
            name='usage_count',
            field=models.IntegerField(default=0, verbose_name='Кол-во использований'),
        ),
    ]
