# Generated by Django 4.2.3 on 2024-05-15 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Имя датчика')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('owner', models.CharField(blank=True, max_length=100, verbose_name='Владелец')),
                ('date_added', models.DateTimeField(auto_now=True, verbose_name='Дата добавления')),
                ('inclusions', models.IntegerField(default=0, verbose_name='Количество включений')),
                ('power', models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Мощность')),
                ('watt', models.IntegerField(default=0, verbose_name='Потребление мощности')),
                ('volt', models.IntegerField(default=0, verbose_name='Электрическое напряжение')),
                ('work', models.BooleanField(default=True, verbose_name='Онлайн')),
                ('blocked', models.BooleanField(default=False, verbose_name='Заблокирован')),
                ('start', models.BooleanField(default=False, verbose_name='Старт')),
                ('temperature', models.FloatField(default=0, verbose_name='Температура')),
                ('fan_speed', models.IntegerField(default=0, verbose_name='Скорость кулера')),
                ('ip_address', models.CharField(blank=True, max_length=15, verbose_name='IP Адрес')),
                ('mac_address', models.CharField(blank=True, max_length=20, verbose_name='MAC Адрес')),
                ('confirmed', models.BooleanField(default=False, verbose_name='Подтвержден администратором')),
                ('version', models.CharField(blank=True, max_length=15, verbose_name='Версия прошивки')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='Время обработки (мс)')),
                ('city', models.ManyToManyField(blank=True, to='esp_sensor.city', verbose_name='Город')),
                ('country', models.ManyToManyField(blank=True, to='esp_sensor.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Датчик',
                'verbose_name_plural': 'Датчики',
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('log_type', models.CharField(max_length=20)),
                ('previous_power', models.IntegerField(blank=True, null=True)),
                ('previous_watt', models.IntegerField(blank=True, null=True)),
                ('previous_volt', models.IntegerField(blank=True, null=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esp_sensor.sensor')),
            ],
            options={
                'verbose_name': 'Логи',
                'verbose_name_plural': 'Логи',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ManyToManyField(blank=True, to='esp_sensor.country', verbose_name='Страна'),
        ),
    ]
