# Generated by Django 4.1.5 on 2024-02-21 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SensorData',
        ),
    ]
