# Generated by Django 4.2.3 on 2024-05-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esp_sensor', '0002_firmware'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='firmware',
            options={'verbose_name': 'Прошивка', 'verbose_name_plural': 'Прошивки'},
        ),
        migrations.AlterField(
            model_name='firmware',
            name='version',
            field=models.CharField(max_length=10, verbose_name='Версия'),
        ),
    ]
