# Generated by Django 4.1.5 on 2023-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0002_alter_city_id_alter_country_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='volt',
            field=models.IntegerField(default=0, verbose_name='Потребление'),
        ),
    ]
