# Generated by Django 4.2.3 on 2024-03-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esp_sensor', '0003_sensor_blocked_alter_sensor_watt'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='fan_speed',
            field=models.IntegerField(default=0, verbose_name='Скорость кулера'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temperature',
            field=models.FloatField(default=0, verbose_name='Температура'),
        ),
    ]
