# Generated by Django 4.2.3 on 2024-05-24 10:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0003_alter_firmware_options_alter_firmware_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='power',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Мощность %'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='volt',
            field=models.IntegerField(default=0, verbose_name='Электрическое напряжение Вольт'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='watt',
            field=models.IntegerField(default=0, verbose_name='Потребление мощности Ватт'),
        ),
    ]
