# Generated by Django 4.1.5 on 2024-02-07 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0005_sensorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlog',
            name='previous_power',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='volt',
            field=models.IntegerField(default=0, verbose_name='Электрическое напряжение'),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='log_type',
            field=models.CharField(max_length=20),
        ),
    ]
