# Generated by Django 4.2.3 on 2024-03-22 06:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('esp_sensor', '0005_sensor_previous_fan_speed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='previous_fan_speed',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='previous_temperature',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='previous_volt',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='previous_watt',
        ),
    ]
