# Generated by Django 4.2.3 on 2024-05-29 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0005_sensorlog_is_anomalous_sensorlog_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorlog',
            name='is_anomalous',
        ),
        migrations.RemoveField(
            model_name='sensorlog',
            name='recommendation',
        ),
    ]
