# Generated by Django 4.1.5 on 2024-04-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0006_remove_sensor_previous_fan_speed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='date_added',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата добавления'),
        ),
    ]
