# Generated by Django 4.1.5 on 2024-02-07 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0006_sensorlog_previous_power_alter_sensor_volt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorlog',
            name='volt',
            field=models.IntegerField(default=0, verbose_name='Электрическое напряжение'),
        ),
        migrations.AddField(
            model_name='sensorlog',
            name='watt',
            field=models.IntegerField(default=0, verbose_name='Измерение мощности'),
        ),
    ]
