# Generated by Django 4.2.3 on 2024-06-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esp_sensor', '0006_remove_sensorlog_is_anomalous_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='tampered',
            field=models.BooleanField(default=False, verbose_name='Устройство вскрыто'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='tampered_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время вскрытия'),
        ),
    ]
