# Generated by Django 4.1.5 on 2024-02-07 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0007_sensorlog_volt_sensorlog_watt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorlog',
            name='volt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sensorlog',
            name='watt',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
