# Generated by Django 4.2.3 on 2024-04-11 14:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esp_sensor', '0008_sensor_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
