# Generated by Django 4.1.5 on 2024-02-07 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0008_alter_sensorlog_volt_alter_sensorlog_watt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorlog',
            old_name='volt',
            new_name='previous_volt',
        ),
        migrations.RenameField(
            model_name='sensorlog',
            old_name='watt',
            new_name='previous_watt',
        ),
    ]
