# Generated by Django 4.1.5 on 2024-02-08 13:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0009_rename_volt_sensorlog_previous_volt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время записи')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='esp_sensor.sensor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
