# Generated by Django 4.1.5 on 2024-04-17 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0010_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
