# Generated by Django 4.1.5 on 2024-05-06 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esp_sensor', '0011_delete_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sensorlog',
            options={'verbose_name': 'Логи', 'verbose_name_plural': 'Логи'},
        ),
        migrations.AddField(
            model_name='sensor',
            name='confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден администратором'),
        ),
    ]
