# Generated by Django 4.2.3 on 2024-05-09 12:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('esp_sensor', '0012_alter_sensorlog_options_sensor_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='mac_address',
            field=models.CharField(blank=True, max_length=20, verbose_name='MAC Адрес'),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='ip_address',
            field=models.CharField(blank=True, max_length=15, verbose_name='IP Адрес'),
        ),
    ]
